config/routes.rb
Rails.application.routes.draw do

  
  get 'start' => 'import#start', as: :start
  post 'import' => 'import#import', as: :import

  resources :categories do
    resources :products
  end
  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :products
end

app/models/csv_importer.rb
require 'open-uri'

module CsvImporter
  DEFAULT_LOCATION = "https://dl.dropboxusercontent.com/u/6582068/products.csv"

  class ImportError < StandardError; end;

  # Import a csv file from a remote location such as 
  # "https://dl.dropboxusercontent.com/u/6582068/products.csv" or from a
  # local file such as "#{Rails.root}/db/csv/products.csv", it returns true
  # if the import is successful, or false if any exceptions thrown during the 
  # import.
  # 
  # The csv file should have the following columns: ProductID, Category,
  # Product Name and Price, and the ProductID should be unique. 
  # The import is idempotent, which means that if the category or the product already
  # exists in database, it will be ignored
  def self.import csv_location = DEFAULT_LOCATION
    csv = SmarterCSV.process(open(csv_location.to_s))
    csv.each do |row|
      category_name = row.delete(:category)
      category = Category.find_or_create_by!(name: category_name)
      product = Product.find_by(productid: row[:productid])
      unless product
        product = Product.create!(row.merge(category: category))
      end
    end
    true
  rescue => e
    Rails.logger.error("Error when import from #{csv_location}: #{e}")
    false
  end

  # The function is the same as import, but it will raise an CsvImporter::ImportError
  # if the import is failed
  def self.import! csv_location = DEFAULT_LOCATION
    unless self.import csv_location
      raise ImportError, "Error occured when import from #{csv_location}", caller
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :product_name, presence: true
  validates :productid, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  belongs_to :category
  validates_presence_of :category

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(:name)
  end
end

app/controllers/import_controller.rb
class ImportController < ApplicationController

  def start
    
  end

  def import
    if CsvImporter.import
      flash[:notice] = "Import Complete"
    else
      flash[:error] = "Import Failed"
    end
    redirect_to start_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @category = Category.find(params[:category_id])
    @products = @category.products.order(:product_name).paginate(page: params[:page], per_page: 5)    
  end

  def show
    @product = Product.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Creates a <li> item for the nav bar, if the current controller's name
  # equals controller_name, the <li> will add 'active' class
  def nav_list_item_for_controller controller_name, path
    content_tag(:ul, class: 'nav navbar-nav') do
      li_options = {}
      li_options[:class] = 'active' if controller.controller_name == controller_name

      content_tag(:li, li_options) do 
        link_to controller_name.humanize, path
      end
    end
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="table table-striped">
  <tbody>
    <% @categories.each do |category| -%>
      <tr>
        <td><%= link_to category.name, category_products_path(category) -%></td>
      </tr>
    <% end -%>
  </tbody>
</table>

app/views/import/new.html.erb
<h3>Import CSV</h3>

<%= button_to 'Trigger Import', import_path, { class: 'btn btn-success'} -%>

app/views/import/start.html.erb
<h1>Import CSV</h1>

<%= button_to 'Trigger Import', import_path, { class: 'btn btn-success'} -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dcstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'DCStore', root_path, class: 'navbar-brand' -%>
      </div>
      
      <div class="collapse navbar-collapse">
        <%= nav_list_item_for_controller 'categories', root_path -%>
        <%= nav_list_item_for_controller 'import', start_path -%>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= render 'shared/notice' -%>
            <%= yield %> 
          </div>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/products/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Home', root_path -%></li>
  <li class="active"><%= @category.name -%></li>
  
</ol>

<h1><%= @category.name -%></h1>

<table class="table table-striped">
  <tbody>
    <% @products.each do |product| -%>
      <tr>
        <td><%= link_to product.product_name, category_product_path(@category, product) -%></td>
      </tr>
    <% end -%>
  </tbody>
</table>

<%= will_paginate @products, class: 'pagination center-block' -%>

app/views/products/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Home', root_path -%></li>
  <li><%= link_to @product.category.name, category_products_path(@product.category) -%></li>
  <li class="active"><%= @product.product_name -%></li>
</ol>

<h1><%= @product.product_name -%></h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 text-right"><strong>Product Id: </strong></div>
    <div class="col-md-10"><%= @product.productid -%></div>
  </div>

  <div class="row">
    <div class="col-md-2 text-right"><strong>Product Name: </strong></div>
    <div class="col-md-10"><%= @product.product_name -%></div>
  </div>

  <div class="row">
    <div class="col-md-2 text-right"><strong>Price: </strong></div>
    <div class="col-md-10"><%= number_to_currency(@product.price) -%></div>
  </div>
</div>

app/views/shared/_notice.html.erb
<% if flash[:notice] -%>
  <div class="alert alert-success">
    <%= flash[:notice] -%>
  </div>
<% end -%>
<% if flash[:error] -%>
  <div class="alert alert-danger">
    <%= flash[:error] -%>
  </div>
<% end -%>